<script setup lang="ts">
import axios from 'axios';
import { computed, ref } from 'vue';
import { usePage } from '@inertiajs/vue3';

const props = defineProps<{ post: any }>();
const page = usePage<any>();
const currentUser = computed(() => page.props.auth?.user || {});
const draft = ref(''), busy = ref(false), showAll = ref(false), replyFor = ref<any>(null), replyDraft = ref('');
const editing = ref<any>(null), editDraft = ref(''), editBusy = ref(false), menuFor = ref<number | null>(null), pickerFor = ref<number | null>(null);
const deleteTarget = ref<any>(null), error = ref('');
const loadingComments = ref(false), loadingReplies = ref<number | null>(null);
const suggestions = ref<any[]>([]), mentionIds = ref<number[]>([]), mentionOpen = ref(false), selectedSuggestion = ref(0);
let searchTimer: any;
const types = ['👍', '❤️', '😂', '😮', '😢', '😡'];
const visible = computed(() => showAll.value ? props.post.comments : props.post.comments.slice(0, 2));
const ago = (v: string) => { const s = Math.floor((Date.now() - new Date(v).getTime()) / 1000); return s < 60 ? 'Just now' : s < 3600 ? `${Math.floor(s / 60)}m` : s < 86400 ? `${Math.floor(s / 3600)}h` : `${Math.floor(s / 86400)}d`; };
const avatar = (u: any) => u.avatar_url;
function resetMentions() { mentionIds.value = []; suggestions.value = []; mentionOpen.value = false; }
function findMention(value: string) { const match = value.match(/(^|\s)@([^\s@]*)$/); return match?.[2] || ''; }
function searchMentions(value: string) { const term = findMention(value); clearTimeout(searchTimer); if (term.length < 2) { suggestions.value = []; mentionOpen.value = false; return; } searchTimer = setTimeout(async () => { try { const { data } = await axios.get('/social/search', { params: { q: term } }); suggestions.value = data.users || []; selectedSuggestion.value = 0; mentionOpen.value = !!suggestions.value.length; } catch { suggestions.value = []; } }, 220); }
function chooseMention(user: any, target: 'comment' | 'reply' | 'edit') { const refTarget = target === 'comment' ? draft : target === 'reply' ? replyDraft : editDraft; refTarget.value = refTarget.value.replace(/(^|\s)@([^\s@]*)$/, `$1@${user.name} `); mentionIds.value = [...new Set([...mentionIds.value, user.id])]; mentionOpen.value = false; }
function keydown(event: KeyboardEvent, target: 'comment' | 'reply' | 'edit') { if (mentionOpen.value) { if (event.key === 'ArrowDown') { event.preventDefault(); selectedSuggestion.value = Math.min(selectedSuggestion.value + 1, suggestions.value.length - 1); } else if (event.key === 'ArrowUp') { event.preventDefault(); selectedSuggestion.value = Math.max(selectedSuggestion.value - 1, 0); } else if (event.key === 'Enter' && suggestions.value[selectedSuggestion.value]) { event.preventDefault(); chooseMention(suggestions.value[selectedSuggestion.value], target); } else if (event.key === 'Escape') { mentionOpen.value = false; } return; } if (target === 'edit' && event.key === 'Escape') cancelEdit(); if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); target === 'comment' ? submit() : target === 'reply' ? submitReply() : saveEdit(); } }
async function submit() { if (!draft.value.trim() || busy.value) return; busy.value = true; error.value = ''; try { const { data } = await axios.post(`/posts/${props.post.id}/comments`, { content: draft.value, mentions: mentionIds.value }); props.post.comments.unshift(data.data); props.post.comments_count++; draft.value = ''; resetMentions(); } catch (e: any) { error.value = e.response?.data?.message || 'Could not post your comment.'; } finally { busy.value = false; } }
function openReply(comment: any) { replyFor.value = comment; replyDraft.value = `@${comment.user.name} `; mentionIds.value = [comment.user_id]; }
async function submitReply() { if (!replyFor.value || !replyDraft.value.trim() || busy.value) return; busy.value = true; try { const { data } = await axios.post(`/posts/${props.post.id}/comments`, { content: replyDraft.value, parent_id: replyFor.value.id, mentions: mentionIds.value }); replyFor.value.replies ||= []; replyFor.value.replies.unshift(data.data); replyFor.value.replies_count = (replyFor.value.replies_count || 0) + 1; replyDraft.value = ''; replyFor.value = null; resetMentions(); } catch (e: any) { error.value = e.response?.data?.message || 'Could not post your reply.'; } finally { busy.value = false; } }
async function react(comment: any, reaction: string) { const before = comment.my_reaction; comment.my_reaction = before === reaction ? null : reaction; try { const { data } = await axios.post(`/comments/${comment.id}/reactions`, { reaction }); Object.assign(comment, data.data); } catch { comment.my_reaction = before; error.value = 'Could not save reaction.'; } finally { pickerFor.value = null; } }
function beginEdit(comment: any) { editing.value = comment; editDraft.value = comment.content; menuFor.value = null; }
function cancelEdit() { editing.value = null; editDraft.value = ''; resetMentions(); }
async function saveEdit() { if (!editing.value || !editDraft.value.trim() || editBusy.value) return; editBusy.value = true; try { const { data } = await axios.put(`/comments/${editing.value.id}`, { content: editDraft.value, mentions: mentionIds.value }); Object.assign(editing.value, data.data); cancelEdit(); } catch (e: any) { error.value = e.response?.data?.message || 'Could not update comment.'; } finally { editBusy.value = false; } }
async function destroy() { const c = deleteTarget.value; if (!c) return; try { await axios.delete(`/comments/${c.id}`); const remove = (list: any[]) => { const i = list.findIndex(x => x.id === c.id); if (i >= 0) list.splice(i, 1); else list.forEach(x => remove(x.replies || [])); }; remove(props.post.comments); props.post.comments_count--; deleteTarget.value = null; } catch { error.value = 'Could not delete comment.'; } }
function report(comment: any) { menuFor.value = null; axios.post(`/comments/${comment.id}/reports`, { reason: 'Reported from comment menu' }).then(() => error.value = 'Comment reported.').catch(() => error.value = 'Could not report comment.'); }
const total = (c: any) => Object.values(c.reactions || {}).reduce((n: number, v: any) => n + Number(v), 0);
async function loadComments() { if (showAll.value) { showAll.value = false; return; } loadingComments.value = true; try { const { data } = await axios.get(`/posts/${props.post.id}/comments`); props.post.comments = data.data; showAll.value = true; } catch { error.value = 'Could not load comments.'; } finally { loadingComments.value = false; } }
async function loadReplies(comment: any) { loadingReplies.value = comment.id; try { const { data } = await axios.get(`/comments/${comment.id}/replies`); comment.replies = data.data; } catch { error.value = 'Could not load replies.'; } finally { loadingReplies.value = null; } }
</script>

<template>
  <section class="space-y-3 px-4 py-3" @click="menuFor = null; pickerFor = null">
    <button v-if="post.comments_count > visible.length || showAll" type="button" @click.stop="loadComments" :disabled="loadingComments" class="text-sm font-semibold text-slate-500 hover:underline">{{ loadingComments ? 'Loading comments…' : showAll ? 'Show fewer comments' : `View ${post.comments_count - visible.length} more comments` }}</button>
    <div v-for="comment in visible" :key="comment.id" class="flex gap-2">
      <span class="grid h-8 w-8 shrink-0 place-items-center overflow-hidden rounded-full bg-slate-200 text-xs font-bold text-slate-600"><img v-if="avatar(comment.user)" :src="avatar(comment.user)" class="h-full w-full object-cover" alt=""><template v-else>{{ comment.user.name?.[0] }}</template></span>
      <div class="min-w-0 flex-1">
        <template v-if="editing?.id === comment.id"><textarea v-model="editDraft" @input="searchMentions(editDraft)" @keydown="keydown($event, 'edit')" rows="2" class="w-full resize-none rounded-xl border-slate-200 text-sm focus:border-indigo-300 focus:ring-indigo-300"/><div class="mt-1 flex gap-2"><button @click="saveEdit" :disabled="editBusy" class="rounded-lg bg-indigo-600 px-3 py-1 text-xs font-semibold text-white">{{ editBusy ? 'Saving…' : 'Save' }}</button><button @click="cancelEdit" class="text-xs font-semibold text-slate-500">Cancel</button></div></template>
        <template v-else><div class="group relative inline-block max-w-full rounded-2xl bg-slate-100 px-3.5 py-2 pr-8 text-sm"><b class="block text-[13px] text-slate-900">{{ comment.user.name }}</b><p class="whitespace-pre-wrap break-words text-slate-700">{{ comment.content }}</p><button @click.stop="menuFor = menuFor === comment.id ? null : comment.id" class="absolute right-1 top-1 hidden h-6 w-6 rounded-full text-slate-500 hover:bg-slate-200 group-hover:block focus:block" aria-label="Comment options">•••</button><div v-if="menuFor === comment.id" @click.stop class="absolute right-0 top-7 z-20 w-28 rounded-lg bg-white p-1 shadow-lg ring-1 ring-slate-200"><button v-if="comment.user_id === currentUser.id" @click="beginEdit(comment)" class="w-full rounded px-2 py-1.5 text-left text-xs hover:bg-slate-50">Edit</button><button v-if="comment.user_id === currentUser.id" @click="deleteTarget = comment; menuFor = null" class="w-full rounded px-2 py-1.5 text-left text-xs text-red-600 hover:bg-red-50">Delete</button><button v-else @click="report(comment)" class="w-full rounded px-2 py-1.5 text-left text-xs hover:bg-slate-50">Report</button></div></div>
          <div class="relative flex items-center gap-3 px-2 pt-1 text-xs font-semibold text-slate-500"><button @click.stop="react(comment, comment.my_reaction || '👍')" @mouseenter="pickerFor = comment.id" class="hover:underline" :class="comment.my_reaction ? 'text-indigo-600' : ''">{{ comment.my_reaction || 'Like' }}</button><button @click.stop="openReply(comment)" class="hover:underline">Reply</button><time>{{ ago(comment.created_at) }}</time><span v-if="comment.updated_at !== comment.created_at">Edited</span><span v-if="total(comment)" class="ml-auto rounded-full bg-white px-1.5 shadow-sm">{{ Object.keys(comment.reactions || {}).slice(0, 3).join('') }} {{ total(comment) }}</span><div v-if="pickerFor === comment.id" @mouseleave="pickerFor = null" class="absolute bottom-5 left-0 z-20 flex rounded-full bg-white p-1 shadow-xl ring-1 ring-slate-200"><button v-for="r in types" :key="r" @click="react(comment, r)" class="grid h-8 w-8 place-items-center rounded-full text-lg hover:bg-slate-100">{{ r }}</button></div></div>
        </template>
        <div v-if="comment.replies?.length" class="mt-2 space-y-2 border-l-2 border-slate-100 pl-3"><div v-for="reply in comment.replies" :key="reply.id" class="flex gap-2"><span class="grid h-7 w-7 shrink-0 place-items-center overflow-hidden rounded-full bg-slate-200 text-[10px] font-bold"><img v-if="avatar(reply.user)" :src="avatar(reply.user)" class="h-full w-full object-cover" alt=""><template v-else>{{ reply.user.name?.[0] }}</template></span><div><div class="rounded-2xl bg-slate-100 px-3 py-1.5 text-sm"><b class="text-[12px]">{{ reply.user.name }}</b><p class="whitespace-pre-wrap break-words text-slate-700">{{ reply.content }}</p></div><div class="flex gap-3 px-2 pt-1 text-xs font-semibold text-slate-500"><button @click="react(reply, reply.my_reaction || '👍')">{{ reply.my_reaction || 'Like' }}</button><button @click="openReply(comment)">Reply</button><span>{{ ago(reply.created_at) }}</span></div></div></div></div>
        <button v-if="comment.replies_count > comment.replies?.length" @click="loadReplies(comment)" :disabled="loadingReplies === comment.id" class="mt-2 text-xs font-semibold text-slate-500 hover:underline">{{ loadingReplies === comment.id ? 'Loading replies…' : `View ${comment.replies_count - comment.replies.length} replies` }}</button>
        <form v-if="replyFor?.id === comment.id" @submit.prevent="submitReply" class="relative mt-2 flex gap-2"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-600 text-xs text-white">{{ currentUser.name?.[0] }}</span><textarea v-model="replyDraft" @input="searchMentions(replyDraft)" @keydown="keydown($event, 'reply')" rows="1" class="min-w-0 flex-1 resize-none rounded-full border-0 bg-slate-100 px-3 py-2 text-sm" placeholder="Write a reply…"/><button class="text-xs font-semibold text-indigo-600">Reply</button></form>
      </div>
    </div>
    <form @submit.prevent="submit" class="relative flex items-center gap-2"><span class="grid h-8 w-8 shrink-0 place-items-center overflow-hidden rounded-full bg-blue-600 text-xs font-bold text-white"><img v-if="currentUser.avatar_url" :src="currentUser.avatar_url" class="h-full w-full object-cover" alt=""><template v-else>{{ currentUser.name?.[0] }}</template></span><textarea v-model="draft" @input="searchMentions(draft)" @keydown="keydown($event, 'comment')" rows="1" class="min-w-0 flex-1 resize-none rounded-full border-transparent bg-slate-100 px-4 py-2 text-sm focus:border-indigo-300 focus:bg-white focus:ring-indigo-300" placeholder="Write a comment…"/><button :disabled="!draft.trim() || busy" class="text-sm font-semibold text-indigo-600 disabled:opacity-40">{{ busy ? '…' : 'Post' }}</button></form>
    <div v-if="mentionOpen" class="relative"><div class="absolute bottom-0 left-10 z-30 w-64 rounded-xl bg-white p-1 shadow-xl ring-1 ring-slate-200"><button v-for="(user, i) in suggestions" :key="user.id" @mousedown.prevent="chooseMention(user, replyFor ? 'reply' : editing ? 'edit' : 'comment')" class="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm" :class="i === selectedSuggestion ? 'bg-indigo-50' : 'hover:bg-slate-50'"><span class="grid h-7 w-7 place-items-center overflow-hidden rounded-full bg-slate-200"><img v-if="user.avatar_url" :src="user.avatar_url" class="h-full w-full object-cover" alt=""></span><span class="min-w-0"><b class="block truncate">{{ user.name }}</b><small v-if="user.username" class="text-slate-500">@{{ user.username }}</small></span></button></div></div>
    <p v-if="error" class="text-xs text-red-600">{{ error }}</p>
    <div v-if="deleteTarget" class="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><div class="w-full max-w-sm rounded-2xl bg-white p-5 shadow-2xl"><h3 class="font-bold">Delete comment?</h3><p class="mt-2 text-sm text-slate-600">Are you sure you want to delete this comment?</p><div class="mt-5 flex justify-end gap-2"><button @click="deleteTarget = null" class="rounded-lg px-3 py-2 text-sm font-semibold">Cancel</button><button @click="destroy" class="rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white">Delete</button></div></div></div>
  </section>
</template>
