<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import axios from 'axios';
import { ref } from 'vue';
const props = defineProps<{ term: string; type: string; people: any; posts: any }>();
const people = ref(props.people?.data || []);
const action = async (person: any) => { if (!person.friendship) person.friendship = (await axios.post(`/users/${person.id}/friendships`)).data.data; };
</script>
<template><Head :title="`Search: ${term}`"/><AuthenticatedLayout><main class="mx-auto max-w-4xl p-4 sm:p-6"><h1 class="text-2xl font-bold">Search results for “{{ term }}”</h1><nav class="mt-4 flex gap-2"><Link v-for="tab in ['all','people','posts']" :key="tab" :href="`/search?q=${encodeURIComponent(term)}&type=${tab}`" class="rounded-full px-4 py-2 text-sm font-semibold capitalize" :class="type===tab?'bg-blue-600 text-white':'bg-white text-slate-700'">{{tab}}</Link></nav><section v-if="type !== 'posts'" class="mt-6"><h2 class="text-lg font-bold">People</h2><div v-if="people.length" class="mt-3 grid gap-3 sm:grid-cols-2"><article v-for="person in people" :key="person.id" class="flex gap-3 rounded-xl bg-white p-4 shadow-sm"><div class="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-full bg-indigo-600 font-bold text-white"><img v-if="person.avatar_url" :src="person.avatar_url" class="h-full w-full object-cover"><span v-else>{{person.name?.[0]}}</span></div><div class="min-w-0 flex-1"><Link :href="route('social.profile',person.id)" class="font-semibold hover:underline">{{person.name}}</Link><p class="text-sm text-slate-500">@{{person.username}}</p><p v-if="person.mutual_friends_count" class="mt-1 text-xs text-slate-500">{{person.mutual_friends_count}} mutual friends</p><button v-if="!person.friendship" @click="action(person)" class="mt-2 rounded bg-blue-600 px-3 py-1.5 text-sm font-semibold text-white">Add Friend</button><span v-else class="mt-2 inline-block text-sm font-semibold text-slate-600">{{person.friendship.status==='accepted'?'Friends':person.friendship.sender_id===$page.props.auth.user.id?'Request sent':'Respond in Friends'}}</span></div></article></div><p v-else class="mt-3 rounded-xl bg-white p-8 text-center text-slate-500">No people found. Try another name or username.</p></section><section v-if="type !== 'people'" class="mt-7"><h2 class="text-lg font-bold">Posts</h2><div v-if="posts?.data?.length" class="mt-3 space-y-3"><article v-for="post in posts.data" :key="post.id" class="rounded-xl bg-white p-5 shadow-sm"><Link :href="route('social.profile',post.author.id)" class="font-semibold">{{post.author.name}}</Link><p class="mt-3 whitespace-pre-wrap">{{post.content || 'Media post'}}</p></article></div><p v-else class="mt-3 rounded-xl bg-white p-8 text-center text-slate-500">No posts found for “{{term}}”.</p></section></main></AuthenticatedLayout></template>
